### ISSUE TITLE
Working directory not same as that for the config file

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpnserv2#16]
https://github.com/OpenVPN/openvpnserv2/blob/4b8ec50409eaf764a2be98c04f1991321207dbcd/Service.cs#L282

Here the working directory is `config.configDir` which is the value of `autostart_config_dir` read from the registry. It should be set to the directory of the current ovpn file (`configFile`) to support relative filenames for certificates, keys etc.

**Comment by cron2** [comment]
Now things get interesting... @mattock @flichtenheld... are we currently building openvpnserv2 from sources, or just shipping that old bundle that was done when openvpnserv2 was introduced...?

**Comment by flichtenheld** [comment]
> Now things get interesting... @mattock @flichtenheld... are we currently building openvpnserv2 from sources, or just shipping that old bundle that was done when openvpnserv2 was introduced...?

We ship the old .exe. But we have a working GHA build, so we should be able to produce a new one when we have a fix.

**Comment by cron2** [comment]
Any volunteers?

**Comment by selvanair** [comment]
I had made a patch that time but held back as I've no easy way to test it. If someone could test this, here it is: https://github.com/selvanair/openvpnserv2/commits/master/
