### ISSUE TITLE
Will this affect main openvpn?

### ISSUE THREAD

**Issue by fcore117** [OpenVPN/openvpnserv2#9]
I have removed all net framework from Windows and i hope this wont affect official release of OpenVPN dependency.

**Comment by mattock** [comment]
At worst OpenVPN installer will ask if you want to install .NET framework. You can reject that offer, but then of course won't be able to make use of openvpnserv2 (OpenVPNService).

**Comment by fcore117** [comment]
Thanks, i hope it will be not forced ever and OpenVPN could work basic way at least like now. I mostly use OpenVPN for directly connecting to other pc-s that runs as server mode.
